/* Packages */
export const GET_PACKAGES_REQUEST = "GET_PACKAGES_REQUEST";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_FAILURE = "GET_PACKAGES_FAILURE";
export const RESET_PACKAGES = "RESET_PACKAGES";
export type GET_PACKAGES_REQUEST = typeof GET_PACKAGES_REQUEST;
export type GET_PACKAGES_SUCCESS = typeof GET_PACKAGES_SUCCESS;
export type GET_PACKAGES_FAILURE = typeof GET_PACKAGES_FAILURE;
export type RESET_PACKAGES = typeof RESET_PACKAGES;

export const GET_PACKAGE_REQUEST = "GET_PACKAGE_REQUEST";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_FAILURE = "GET_PACKAGE_FAILURE";
export const RESET_PACKAGE = "RESET_PACKAGE";
export type GET_PACKAGE_REQUEST = typeof GET_PACKAGE_REQUEST;
export type GET_PACKAGE_SUCCESS = typeof GET_PACKAGE_SUCCESS;
export type GET_PACKAGE_FAILURE = typeof GET_PACKAGE_FAILURE;
export type RESET_PACKAGE = typeof RESET_PACKAGE;

/* Marketing tracking parameters */
export const ADD_TRACKING_PARAMETERS = "ADD_TRACKING_PARAMETERS";
export type ADD_TRACKING_PARAMETERS = typeof ADD_TRACKING_PARAMETERS;

/* Navigation */
export const HANDLE_POSTAL_CODE = "HANDLE_POSTAL_CODE";
export const DISPLAY_WE_DELIVER = "DISPLAY_WE_DELIVER";
export const DISPLAY_NO_DELIVERY = "DISPLAY_NO_DELIVERY";
export const DISPLAY_POSTAL_INPUT = "DISPLAY_POSTAL_INPUT";
export const HANDLE_EMAIL_SUCCESS = "HANDLE_EMAIL_SUCCESS";
export const TOGGLE_NAVIGATION_BANNER = "TOGGLE_NAVIGATION_BANNER";
export type HANDLE_POSTAL_CODE = typeof HANDLE_POSTAL_CODE;
export type DISPLAY_WE_DELIVER = typeof DISPLAY_WE_DELIVER;
export type DISPLAY_NO_DELIVERY = typeof DISPLAY_NO_DELIVERY;
export type DISPLAY_POSTAL_INPUT = typeof DISPLAY_POSTAL_INPUT;
export type HANDLE_EMAIL_SUCCESS = typeof HANDLE_EMAIL_SUCCESS;
export type TOGGLE_NAVIGATION_BANNER = typeof TOGGLE_NAVIGATION_BANNER;
export const UPDATE_DELIVERY_AREA = "UPDATE_DELIVERY_AREA";
export type UPDATE_DELIVERY_AREA = typeof UPDATE_DELIVERY_AREA;
export const HIDE_NEW_PRICING_BANNER = "HIDE_NEW_PRICING_BANNER";
export type HIDE_NEW_PRICING_BANNER = typeof HIDE_NEW_PRICING_BANNER;
