const PAGES = {
  ABOUT: 'About Feather',
  CART: 'Cart',
  CHECKOUT: 'Checkout',
  CHECKOUT_SUCCESS: 'Checkout Success',
  CONTACT: 'Contact',
  CURATED_PACKAGE: 'Package Details',
  ERROR: 'Page Not Found',
  FAQ: 'FAQs',
  HOMEPAGE: 'Homepage',
  HOW_IT_WORKS: 'How It Works',
  QUIZ_PACKAGE: 'Quiz Results',
  PACKAGES: 'Package Category',
  PRIVACY: 'Privacy Policy',
  PRODUCT_DETAILS: 'Product Details',
  PRODUCTS: 'Product Category',
  REVIEWS: 'Reviews',
  SEARCH: 'Search',
  TERMS_CONDITIONS: 'Terms And Conditions',
  ACCOUNT_DELIVERY: 'Account Delivery',
  ACCOUNT_FURNITURE: 'Account Furniture',
  ACCOUNT_BILLING: 'Account Plan And Billing',
  ACCOUNT_FAQ: 'Account FAQ',
  ACCOUNT_CHANGE_PASSWORD: 'Account Change Password',
  ACCOUNT_PERKS: 'Account Perks',
  LOGIN: 'Login',
  SETUP_ACCOUNT: 'Setup Account',
  FORGOT_PASSWORD: 'Forgot Password',
  VERIFY: 'Verify Email',
  LANDING_PAGE: 'Promo Landing Page',
  ENTERPRISE: 'Feather for business',
  FLOYD: 'Feather x Floyd landing',
  LOCATION_LANDING: 'Location landing'
};

export default PAGES;
