export const CHECKOUT = {
  CUSTOMER_INFO: "Checkout Customer Info Form Submitted",
  INTENDED_USE: "Checkout Question Intended Use",
  DELIVERY_INFO: "Checkout Delivery Form Submitted",
  CLICK_TOOLTIP: "Checkout Credit Check Tooltip Clicked",
  CREDIT_CHECK: "Checkout Without Credit Check Tried",
  PROMO_CODE: "Coupon Entered",
  PROMO_CLICK: "Checkout Promo Code Field Clicked",
  STEP_VIEWED: "Checkout Step Viewed",
  STEP_COMPLETED: "Checkout Step Completed",
  ZIP_ERROR: "Checkout Zip Code Error",
  STRIPE_ERROR: "Checkout Stripe Error",
  SUCCESS: "Order Completed",
  IMPACT_AFFILIATE_SALE: "Online Sale",
  GOOGLE_API_SCRIPT_ERROR: "Checkout Delivery Google Places Error",
  CUSTOMER_NOT_APPROVED: "Checkout Customer Not Approved",
  ADDITIONAL_INFO_REQUIRED:
    "Checkout Additional Information Required For Credit Check",
  CREDIT_REPORT_NOT_FOUND: "Checkout Credit Report Not Found",
  INVALID_SSN: "Checkout Invalid SSN Submitted",
  OFAC_CHECK_FAILED: "OFAC Check Failed",
  CUSTOMER_INCOME_REQUIRED: "Self Reported Income Required From Customer",
  MAX_TCV_EXCEEDED: "Max Cart Price Threshold Exceeded",
  DEPOSIT_REQUESTED: "Deposit Requested",
};
